// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";

var message = "Log like this!";

console.log(message);

var outputEl = ( document.getElementById("output") );

var maybeEl = (outputEl == null) ? undefined : Caml_option.some(outputEl);

if (outputEl == null) {
  console.log("Couldn't find the output element");
} else {
  (( outputEl.innerText = "minimum viable Reason" ));
}

export {
  message ,
  outputEl ,
  maybeEl ,
  
}
/*  Not a pure module */
